CREATE TYPE message_type AS ENUM ('message', 'reaction');

CREATE TABLE chat_messages (
    -- id is generated by chat-service at WS-ingress time, not by Postgres:
    -- it's what makes the Kafka consumer's insert idempotent (ON CONFLICT
    -- DO NOTHING on a replayed message), same pattern as fraud-detection's
    -- transaction_id-keyed idempotent inserts.
    id              UUID PRIMARY KEY,
    stream_id       UUID NOT NULL,
    user_id         UUID NOT NULL,
    display_name    TEXT NOT NULL,
    type            message_type NOT NULL DEFAULT 'message',
    body            TEXT NOT NULL,
    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_chat_messages_stream_id_created_at ON chat_messages(stream_id, created_at DESC);
